name: 'CI/CD'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build React app
        run: |
          yarn install
          yarn add @babel/plugin-proposal-private-property-in-object -D
          yarn build

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SECRET_KEY }}
          source: "./build/*"
          target: "/root/surgery-front/build"
          
      - name: Move files to Nginx directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SECRET_KEY}}
          script: |
            cd /root/surgery-front/build
            mv * /var/www/myapp/
            
      - name: Restart Nginx to apply changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SECRET_KEY}}
          script: |
            sudo systemctl restart nginx 
          
